export const products = [
  {
    category: 101,
    currency: 'EUR',
    description:
      'A timeless leather handbag with a spacious interior and elegant design.',
    id: 201,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Classic Leather Handbag',
    },
    name: 'Classic Leather Handbag',
    price: 120.99,
    sku: 'HB-CL-201',
    stock: 15,
    url: '/product/classic-leather-handbag',
  },
  {
    category: 101,
    currency: 'EUR',
    description:
      'A modern tote handbag with durable handles and multiple compartments.',
    id: 202,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Modern Tote Handbag',
    },
    name: 'Modern Tote Handbag',
    price: 95.5,
    sku: 'HB-MT-202',
    stock: 8,
    url: '/product/modern-tote-handbag',
  },
  {
    category: 101,
    currency: 'EUR',
    description: 'A luxurious crocodile-pattern handbag for an exclusive look.',
    id: 203,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Luxury Crocodile Handbag',
    },
    name: 'Luxury Crocodile Handbag',
    price: 250.0,
    sku: 'HB-LC-203',
    stock: 0,
    url: '/product/luxury-crocodile-handbag',
  },
  {
    category: 102,
    currency: 'EUR',
    description: 'A compact leather purse with a sleek design and card slots.',
    id: 204,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Compact Leather Purse',
    },
    name: 'Compact Leather Purse',
    price: 45.99,
    sku: 'PR-CL-204',
    stock: 20,
    url: '/product/comapct-leather-purse',
  },
  {
    category: 102,
    currency: 'EUR',
    description:
      'A vibrant fabric purse featuring a floral pattern and a zip closure.',
    id: 205,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Fabric Purse with Floral Design',
    },
    name: 'Fabric Purse with Floral Design',
    price: 30.75,
    sku: 'PR-FL-205',
    stock: 0,
    url: '/product/fabric-purse-with-floral-design',
  },
  {
    category: 103,
    currency: 'EUR',
    description: 'A reusable eco-friendly shopper bag with reinforced handles.',
    id: 206,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Eco-Friendly Shopper Bag',
    },
    name: 'Eco-Friendly Shopper Bag',
    price: 25.0,
    sku: 'SP-EF-206',
    stock: 30,
    url: '/product/eco-friendly-shopper-bag',
  },
  {
    category: 103,
    currency: 'EUR',
    description:
      'A large canvas shopper bag, perfect for groceries or everyday use.',
    id: 207,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Large Canvas Shopper',
    },
    name: 'Large Canvas Shopper',
    price: 40.99,
    sku: 'SP-LC-207',
    stock: 18,
    url: '/product/large-canvas-shopper',
  },
  {
    category: 103,
    currency: 'EUR',
    description:
      'A stylish designer shopper tote with premium fabric and unique patterns.',
    id: 208,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Designer Shopper Tote',
    },
    name: 'Designer Shopper Tote',
    price: 75.0,
    sku: 'SP-DT-208',
    stock: 10,
    url: '/product/designer-shopper-tote',
  },
  {
    category: 103,
    currency: 'EUR',
    description: 'A waterproof shopper bag for rainy days and outdoor use.',
    id: 209,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Waterproof Shopper Bag',
    },
    name: 'Waterproof Shopper Bag',
    price: 50.0,
    sku: 'SP-WP-209',
    stock: 12,
    url: '/product/waterproof-shopper-bag',
  },
  {
    category: 104,
    currency: 'EUR',
    description:
      'An elegant evening clutch with a metallic finish and detachable chain.',
    id: 210,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Elegant Evening Clutch',
    },
    name: 'Elegant Evening Clutch',
    price: 70.0,
    sku: 'CL-EE-210',
    stock: 9,
    url: '/product/elegant-evening-clutch',
  },
  {
    category: 104,
    currency: 'EUR',
    description:
      'A minimalist leather clutch with a zippered closure and a clean design.',
    id: 211,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Minimalist Leather Clutch',
    },
    name: 'Minimalist Leather Clutch',
    price: 55.5,
    sku: 'CL-ML-211',
    stock: 14,
    url: '/product/minimalist-leather-clutch',
  },
  {
    category: 104,
    currency: 'EUR',
    description: 'A bold studded clutch perfect for parties and night outs.',
    id: 212,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Studded Party Clutch',
    },
    name: 'Studded Party Clutch',
    price: 80.9,
    sku: 'CL-SP-212',
    stock: 6,
    url: '/product/studded-party-clutch',
  },
  {
    category: 104,
    currency: 'EUR',
    description: 'A vintage-inspired beaded clutch with intricate detailing.',
    id: 213,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Vintage Beaded Clutch',
    },
    name: 'Vintage Beaded Clutch',
    price: 65.75,
    sku: 'CL-SP-213',
    stock: 3,
    url: '/product/vintage-beaded-clutch',
  },
  {
    category: 104,
    currency: 'EUR',
    description: 'An exquisite silk clutch with embroidered floral patterns.',
    id: 214,
    image: {
      url: 'https://fastly.picsum.photos/id/8/715/950.jpg?hmac=xBYdHSJ2hIdMgblS9S31rxlfJmeSEYiO7QJmeqQDQew',
      alt: 'Silk Embroidered Clutch"',
    },
    name: 'Silk Embroidered Clutch"',
    price: 90.0,
    sku: 'CL-SP-214',
    stock: 7,
    url: '/product/silk-embroidered-clutch',
  },
];
